using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SecurityLibrary
{
    public class Monoalphabetic : ICryptographicTechnique<string, string>
    {
        public string Analyse(string plainText, string cipherText)
        {
            cipherText = cipherText.ToLower();
            plainText = plainText.ToLower();
            List<char> dist = new List<char>();
            for(int i = 0; i < 26; i++)
            {
                dist.Add((char)('a'+i));
            }
            char[] chars = new char[26];
            string key = "";
            for (int i = 0; i < cipherText.Length; i++) {
                int key_indx = (int)(plainText[i] - 'a');
                chars[key_indx] = cipherText[i];
                if(dist.Contains(cipherText[i]))
                    dist.Remove(cipherText[i]);
            }
            int j = 0;
            for (int i = 0; i < chars.Length; i++) {
                if (chars[i] != '\0')
                    key += chars[i];
                else
                {
                    key += dist[j];
                    j++;
                }
            }
            return key;
        }

        public string Decrypt(string cipherText, string key)
        {
            cipherText = cipherText.ToLower();
            key = key.ToLower();
            Dictionary<char, int> key_char_indx = new Dictionary<char, int>();
            for (int i = 0; i < key.Length; i++)
                key_char_indx[key[i]] = i;
            String plainText = "";
            for (int i = 0; i < cipherText.Length; i++)
                plainText += (char)('a' + key_char_indx[cipherText[i]]);
            return plainText;
        }

        public string Encrypt(string plainText, string key)
        {
            plainText = plainText.ToLower();
            String cipherText = "";
            for (int i = 0; i < plainText.Length; i++)
                cipherText += key[plainText[i]-'a'];
            return cipherText;
        }

        /// <summary>
        /// Frequency Information:
        /// E   12.51%
        /// T	9.25
        /// A	8.04
        /// O	7.60
        /// I	7.26
        /// N	7.09
        /// S	6.54
        /// R	6.12
        /// H	5.49
        /// L	4.14
        /// D	3.99
        /// C	3.06
        /// U	2.71
        /// M	2.53
        /// F	2.30
        /// P	2.00
        /// G	1.96
        /// W	1.92
        /// Y	1.73
        /// B	1.54
        /// V	0.99
        /// K	0.67
        /// X	0.19
        /// J	0.16
        /// Q	0.11
        /// Z	0.09
        /// </summary>
        /// <param name="cipher"></param>
        /// <returns>Plain text</returns>
        public string AnalyseUsingCharFrequency(string cipher)
        {

            Dictionary<char, char> givenfreq = new Dictionary<char, char>
            {

            {'e', 'a'}, {'t', 'a'}, {'a', 'a'}, {'o', 'a'}, {'i', 'a'},
            {'n', 'a'}, {'s', 'a'}, {'r', 'a'}, {'h', 'a'}, {'l', 'a'},
            {'d', 'a'}, {'c', 'a'}, {'u', 'a'}, {'m', 'a'}, {'f', 'a'},
            {'p', 'a'}, {'g', 'a'}, {'w', 'a'}, {'y', 'a'}, {'b', 'a'},
            {'v', 'a'}, {'k', 'a'}, {'x', 'a'}, {'j', 'a'}, {'q', 'a'},
            {'z', 'a'}

            };

            //String cipher = "MXOBSUHYLRXVPRQWKQHAWPRQWKPHPEHUVXSGDWHILUVWVFUHHQHGLWRULDOEDFNRQPBVRDSERAZKBLVLWWKDWXVHRIWKHHQJOLVKODQJXDJHLVJHWWLQJVRYHUBVORSSBKRZORQJDJRZDVLWZKHQJUDPPDUFHDVHGWREHDQHVVHQWLDOHOHPHQWRIZULWLQJDGHFHQWHVVDBDZKLOHDJRWKHUHZDVDFDPSDLJQWRGRDZDBZLWKWKHDEHUUDQWDSRVWURSKHQRZLWVHHPVZHQHHGDQHZFDPSDLJQWRFRQWHQGZLWKWKHDEHUUDQWKBSKHQBHVLNQRZWKHUHLVDYDVWGLIIHUHQFHEHWZHHQDEODFNFDEGULYHUDQGDEODFNFDEGULYHUEXWQRQHRIPBUHIHUHQFHERRNVLQYLWHVKBSKHQDWLRQRIEODFNFDERUGULYHUDQHAWUHPHHADPSOHSHUKDSVEXWLPJHWWLQJWLUHGRIVRUWLQJRXWKBSKHQDWHGZRUGVDQGUHSODFLQJWKHKBSKHQZLWKDFRPPDRUVHPLFRORQRUFUHDWLQJDQHZVHQWHQFHQRRIFRXUVHLPQRWSHUIHFWQRRQHLVEXWLQRWRQOBDEKRUWKHLQDSSURSULDWHXVHRIDKBSKHQLDOVRUHFRJQLVHDVSOLWLQILQLWLYHZKHQLVHHRQHLWPDBEHDFFHSWDEOHIRUWKHVWDUVKLSHQWHUSULVHWREROGOBJREXWLGRQRWWKLQNWKDWORFDORUJDQLVDWLRQVVKRXOGEHHQFRXUDJHGWRSURDFWLYHOBHQJDJHGHSDUWPHQWRIZRUNDQGSHQVLRQVSUHVVUHOHDVHLUHOBRQMXOLHWRFKHFNWKHSURRIFRSBRIXSGDWHEHIRUHBRXVHHLWDQGVKHZRQWOHWFDUHOHVVXVHRIJUDPPDUVOLSWKURXJKRRSVLVKRXOGQRZVDBLXVHGWRUHOBRQMXOLHDVLZURWHWKDWEHIRUHVKHKDQGHGLQKHUQRWLFHQREHIRUHBRXDVNLGRQWWKLQNLWZDVDQBWKLQJLVDLGRUGLGVSHFLILFDOOBDVPDQBUHDGHUVZLOONQRZDGVHWSURYLGHGRIILFHVSDFHIRUWKHDGPLQLVWUDWLRQIXQFWLRQVRIQDHJDZLWKMXOLHZRUNLQJIRUQDHJDIRUWZHOYHKRXUVDZHHNLQWKDWVSDFHWKDWFRQWUDFWFDPHWRDQDEUXSWHQGLQPDBDQGLFDQQRWILQGZRUNZLWKLQWKHDGVHWVHWXSWRPDNHXSWKRVHPLVVLQJKRXUVVRUDWKHUWKDQWUBWRILQGDVHFRQGSDUWWLPHMREMXOLHKDVIRXQGKHUVHOIIXOOWLPHZRUNVKHZLOOEHJUHDWOBPLVVHGQRWOHDVWIRUKHUDELOLWBWRVSRWDQDEHUUDQWKBSKHQRUDSRVWURSKHFKDQJHVDUHDIRRWZHOOWKHBZRXOGKDYHWREHZRXOGQWWKHBGDZQBHVWKHRQHZKRZULWHVWKHIXQQBFRPPHQWVLQXSGDWHZLOOEHWDNLQJRYHUMXOLHVMRERIWKHQHZVSDSHUVWKHWLPLQJLVULJKWDVKHUBRXQJHVWVWDUWVIXOOWLPHVFKRROLQVHSWHPEHUUXWKZDUQHUZKRPPDQBRIBRXDOUHDGBNQRZDVDGVHWVGDWDPDQDJHUDOVRLQFRQWURORIWKHZHEVLWHZLOOEHWDNLQJRYHUDVPHPEHUVKLSVHFUHWDUBDVIRUKHOSLQWKHRIILFHLPLQWHUYLHZLQJIRXUSHRSOHWRPRUURZDQGHASHFWWREHDEOHWRDSSRLQWRQHRIWKHPWRVWDUWRQDXJXVWWKDWJLYHVKHUWKHBDUHDOOIHPDOHWKUHHZHHNVWRILQGKHUIHHWEHIRUHLJRRQKROLGDBIRUDZHHNLQHYHUWKRXJKWWKDWLGEHEOHVVLQJPRELOHSKRQHVEXWLWKLQNWKDWLWPLJKWEHQHHGHGDQGWKHIDPLOBZLOOIRURQFHKDYHWRDFFHSWLWWKHZLGHUZRUOGWKHOVFKDVEHHQWDNLQJDELWRIDKDPPHULQJWKLVPRQWKZLWKWKHDVVRFLDWLRQRIFROOHJHVVWLOODVVHUWLQJWKDWWKHUHDUHFOHDUWHQVLRQVEHWZHHQWKHFHQWUHDQGWKHDUPVDQGLQVWLWXWHRIGLUHFWRUVVDBLQJWKDWWKHRUJDQLVDWLRQKDVPDGHOLWWOHLIDQBLPSDFWRQEXVLQHVVWKHIXQGLQJRIOHDUQLQJDQGWKHSHRSOHZKRXQGHUWDNHLWFRQWLQXHVWRGRPLQDWHWKHHGXFDWLRQDOSUHVVZKLOVWWKHSURYLVLRQRIDGGLWLRQDOPRQHBXQGHUWKHFRPSUHKHQVLYHVSHQGLQJUHYLHZLVZHOFRPHGLWVQRWHQRXJKLVLWHYHULWVHHPVWKHWKHSRZHUVWKDWEHDUHZDNLQJXSWRWKHLGHDWKDWPDBEHMXVWPDBEHDLPLQJIRUDSDSHUOHVVVRFLHWBZDVQRWVXFKDJRRGLGHDDWOHDVWQRWXQWLOBRXFDQEHFHUWDLQRIEHLQJDEOHWRUHWULHYHWKHLQIRUPDWLRQFUHDWHGZHOFRPHWRQHZPHPEHUVFDPEULGJHVKLUHJULGIRUOHDUQLQJFRQWDFWOLOBGDLQWHUWHOORJZRRGPDQDJHPHQWFRQVXOWDQWVOWGFRQWDFWYHOPDEHQQHWWWHOGHWDLOVRIWKHZRUNRIWKHVHWZRRUJDQLVDWLRQVZLOOEHSODFHGRQWKHDGVHWZHEVLWHMXVWDVVRRQDVZHJHWWKHPWRWRSRISDJHWRLQGHAFLSGXUJHVFDXWLRQRQHPSORBHHULJKWVUHYLHZSDWULFLDKHZLWWVHFUHWDUBRIVWDWHIRUWUDGHDQGLQGXVWUBKDVWRGDBMXOBODXQFKHGDUHYLHZRIWKHHPSORBPHQWUHODWLRQVDFWWKHUHYLHZZLOOORRNDWFRPSXOVRUBWUDGHXQLRQUHFRJQLWLRQPHDVXUHVDOWKRXJKFKDQJHVZLOOEHOLPLWHGDFFRUGLQJWRWKHGWLWKHFLSGHASUHVVHVFDXWLRQDERXWWKHLQLWLDWLYHGLDQHVLQFODLUOHDGSXEOLFSROLFBDGYLVHUUHVSRQGHGWKHODZLVZRUNLQJZHOODWWKHPRPHQWDQGLVILQHOBEDODQFHGEHWZHHQHPSORBHUVDQGHPSORBHHVIRULQVWDQFHPDQBWUDGHXQLRQVDUHFXUUHQWOBZLQQLQJFODLPVXQGHUWKHDFWZHKRSHWKDWWKHJRYHUQPHQWDOORZVWKLVOHJLVODWLRQWREHGGRZQEHIRUHFKDQJHVDUHFRQVLGHUHGWKHGWLKDVDOVRODXQFKHGDFRQVXOWDWLRQGRFXPHQWWRGDBRQLPSOHPHQWLQJWKHHXGLUHFWLYHRQLQIRUPLQJDQGFRQVXOWLQJVWDIILQWKHXNWKLVLVGXHWRFRPHLQWRHIIHFWLQWKHXNIRURUJDQLVDWLRQVRIPRUHWKDQVWDIIEBPDUFKDQGIRUVPDOOHURUJDQLVDWLRQVEBPDUFKRUJDQLVDWLRQVHPSORBLQJOHVVWKDQSHRSOHDUHOLNHOBWREHHAFOXGHGFLSGSUHVVUHOHDVHMXOBWRWRSRISDJHWRLQGHAMRKQVRQKHUDOGVQHZHUDIRUEULWLVKILUPVQHZSURSRVDOVWRFXWUHGWDSHDQGVDYHVPDOOEXVLQHVVHVDURXQGPLOOLRQDBHDUZHUHXQYHLOHGWRGDBMXOBZLWKWKHSXEOLFDWLRQRIWKHJRYHUQPHQWZKLWHSDSHUPRGHUQLVLQJFRPSDQBODZWKHZKLWHSDSHUUHIOHFWVWKHFKDQJHVLQWKHEXVLQHVVHQYLURQPHQWLQUHFHQWBHDUVSDUWLFXODUOBWKHJURZWKRIVPDOOEXVLQHVVHVDQGDGYDQFHVLQFRPPXQLFDWLRQVWHFKQRORJBDQGLQFOXGHVSODQVWRVLPSOLIBWKHODZDQGUHGXFHEXUGHQVRQVPDOOILUPVLPSURYHWUDQVSDUHQFBWRLQFUHDVHFRQILGHQFHLQEXVLQHVVDQGLPSURYHJRYHUQDQFHWRHQFRXUDJHDQGVXSSRUWUHVSRQVLEOHEXVLQHVVRWKHUNHBSURSRVDOVLQFOXGHGLUHFWRUVGXWLHVZLOOEHVHWRXWFOHDUOBLQVWDWXWHIRUWKHILUVWWLPHFRUSRUDWHGLUHFWRUVZLOOEHSURKLELWHGSULYDWHFRPSDQLHVQRORQJHUZLOOKDYHWRDSSRLQWFRPSDQBVHFUHWDULHVSULYDWHFRPSDQLHVQRORQJHUZLOOKDYHWRKROGDJPVXQOHVVPHPEHUVZDQWWKHPFRPSDQLHVZLOOEHDEOHWRHASORLWWKHLQWHUQHWDQGHPDLOWRPDNHGHFLVLRQVFRPSDQLHVZLOOKDYHVLPSOHUUHSRUWVDQGDFFRXQWVDFFRXQWVZLOOEHILOHGPRUHTXLFNOBZLWKLQVHYHQPRQWKVIRUSULYDWHFRPSDQLHVDQGVLAPRQWKVIRUSXEOLFFRPSDQLHVTXRWHGFRPSDQLHVZLOOKDYHWRSRVWUHSRUWVRQZHEVLWHVEHIRUHWKLVWKHODUJHVWFRPSDQLHVZLOOSXEOLVKDQRSHUDWLQJDQGILQDQFLDOUHYLHZFRPSDQLHVDQGWKHLUGLUHFWRUVFRQYLFWHGRIIORXWLQJFRPSDQBODZFRXOGEHQDPHGLQDFHQWUDOUHJLVWHUWKHZKLWHSDSHULVDYDLODEOHRQOLQHDWZZZGWLJRYXNFRPSDQLHVELOODVXPPDUBRIWKHPHDVXUHVRISDUWLFXODULQWHUHVWWRVPDOOEXVLQHVVLVDOVRDYDLODEOHGWLSUHVVUHOHDVHSMXOBWRWRSRISDJHWRLQGHAFELSUDLVHVFRPSDQBODZUHIRUPSODQVWKHFRQIHGHUDWLRQRIEULWLVKLQGXVWUBFELLVEDFNLQJJRYHUQPHQWSURSRVDOVWRUHIRUPFRPSDQBODZLWLVKRSHGWKDWWKLVZLOOVLPSOLIBWKHUHJLPHIRUVPDOOILUPVZKLOHLPSURYLQJDFFRXQWDELOLWBIRUODUJHURJDQLVDWLRQVWKHFELLVSUDLVLQJJRYHUQPHQWSODQVWRLPSOHPHQWWKHUHFRPPHQGDWLRQVRIWKHFRPSDQBODZUHYLHZLWLVKRSHGWKDWWKLVZLOOPDNHWKHODZFOHDUHUDQGPRUHHIIHFWLYHKUORRNMXOBWRWRSRISDJHWRLQGHASDWULFLDKHZLWWDQQRXQFHVQHZDSSRLQWPHQWVWRWKHVPDOOEXVLQHVVFRXQFLOVHFUHWDUBRIVWDWHIRUWUDGHDQGLQGXVWUBSDWULFLDKHZLWWWRGDBMXOBDQQRXQFHGWKHIXOOQHZPHPEHUVKLSRIWKHVPDOOEXVLQHVVFRXQFLOVEFWKHPHPEHUVZRUNZLWKWKHFKDLUPDQZLOOLDPVDUJHQWWRDGYLVHWKHJRYHUQPHQWRQLVVXHVDIIHFWLQJVPDOOEXVLQHVVHVWKHVEFUHSUHVHQWVDZLGHUDQJHRIVHFWRUVLQFOXGLQJPDQXIDFWXULQJUHWDLOVRFLDOHQWHUSULVHWRXULVPEXVLQHVVVXSSRUWHQYLURQPHQWDOEXVLQHVVHVPHGLDDQGHQWHUWDLQPHQWUHFUXLWPHQWDFFRXQWDQFBDQGDFDGHPLDWKHPHPEHUVKLSUHSUHVHQWVDOOSDUWVRIWKHXNDQGLQFOXGHVSHRSOHRIGLIIHUHQWDJHVDQGEDFNJURXQGVGWLSUHVVUHOHDVHSMXOBXSGDWHFRPPHQWWKHSUHVVUHOHDVHOLVWVWKHSHRSOHZLWKVKRUWELRJVDQGVRPHRIWKHPUHDOOBDUHIURPVPDOOEXVLQHVVHVWRWRSRISDJHWRLQGHAVPDOOEXVLQHVVVHFWRUJURZWKHTXLYDOHQWWRRYHUQHZVWDUWXSVHYHUBGDBQLJHOJULIILWKVKDLOVQHWLQFUHDVHLQEXVLQHVVSRSXODWLRQQHZILJXUHVSXEOLVKHGWRGDBMXOBVKRZWKHUHZDVDQHWLQFUHDVHRIPRUHWKDQILUPVRSHUDWLQJLQWKHXNLQFRPSDUHGWRWKHSUHYLRXVBHDUHTXLYDOHQWWRRYHUQHZEXVLQHVVHVVWDUWLQJXSHYHUBGDBDFFRUGLQJWRQHZVWDWLVWLFVIURPWKHGWLVVPDOOEXVLQHVVVHUYLFHVEVWKHEXVLQHVVSRSXODWLRQWRWDOOHGODVWBHDUFRPSDUHGWRLQWKHBHDURWKHUILQGLQJVVKRZWKHUHZHUHPLOOLRQPRUHEXVLQHVVHVWKDQLQWKHILUVWBHDUIRUZKLFKFRPSDUDEOHILJXUHVDUHDYDLODEOHWKHQXPEHURIPHGLXPVLCHGEXVLQHVVHVUHDFKHGIRUWKHILUVWWLPHLQVHYHQBHDUVDQGDWOHDVWRIEXVLQHVVHVLQDOOLQGXVWULHVZHUHVPHVWKHIXOOVWDWLVWLFVFDQEHGRZQORDGHGIURPWKHVPDOOEXVLQHVVVHUYLFHZHEVLWHDWZZZVEVJRYXNVWDWLVWLFVGWLSUHVVUHOHDVHSMXOBWKHJDPHFRPHVWLPDWHVWKDWZRUOGFXSDEVHQWHHLVPFRVWWKHXNDURXQGPLOOLRQWKLVILJXUHLVRQOBDWHQWKRIWKHSUHGLFWHGFRVWVLQFHPDQBHPSORBHUVZHUHFRRSHUDWLYHDQGDOORZHGHPSORBHHVWRHLWKHUFKDQJHWKHLUKRXUVRUZDWFKWKHPDWFKHVDWZRUNKRZHYHURIIDQVVWLOODGPLWWHGWRWDNLQJDWOHDVWRQHGDBDVVLFNOHDYHLUVHPSORBPHQWUHYLHZLVVXHMXOBWRWRSRISDJHWRLQGHAFRPPXQLFDWLRQVNLOOVODFNLQJDWWKHWRSDFFRUGLQJWRQHZUHVHDUFKIURPWKHDCLCFRUSRUDWLRQEULWDLQVWRSEXVLQHVVOHDGHUVDUHODUJHOBXQKHDUGXQUHFRJQLVHGDQGFRQVLGHUHGXQDEOHWRFRPPXQLFDWHHIIHFWLYHOBEBWKHLUEXVLQHVVSHHUVWKHUHVHDUFKUHYHDOHGWKDWZKLOHRIXNFRPSDQBGLUHFWRUVFRQVLGHUXVEXVLQHVVHAHFXWLYHVWRKDYHDQHAFHOOHQWRUJRRGPHGLDLPDJHDQGUHSXWDWLRQRQOBEHOLHYHWKHVDPHRIXNHAHFXWLYHVLQDGGLWLRQIHHOWKDWWKHPHGLDLPDJHRIWKHXNVOHDGLQJEXVLQHVVHAHFXWLYHVLVLQQHHGRILPSURYHPHQWWUDLQLQJCRQHOHDUQLQJZLUHLVVXHMXOBWRWRSRISDJHWRLQGHAWKHKXPEOHOHDGHUDQDUWLFOHLQEXOOHWSRLQWMXQHLVVXHDUJXHVWKDWKDYLQJDODUJHUWKDQOLIHFRUSRUDWHKHURDVDOHDGHUFDQEHGHWULPHQWDOWRDQRUJDQLVDWLRQWKHPDLQFULWLFLVPVRIWKLVWBSHRIOHDGHUDUHWKDWWKHBDUHVHOIVHUYLQJPRUHLQWHUHVWHGLQVHOISURPRWLRQDQGFHOHEULWBWKDQWHDPZRUNWKHDUWLFOHIXUWKHUVXJJHVWVWKDWLQPDQBFDVHVWKHBIDLOWRDGGYDOXHGRQRWGHOLYHUVXVWDLQDEOHUHVXOWVDQGGRQWZRUNWRLPSURYHSHUIRUPDQFHWKHDUWLFOHWHOOVXVWKDWWUXOBWUDQVIRUPDWLRQDOOHDGHUVKDYHDQHTXDOUDWLRRIKXPLOLWBDQGSURIHVVLRQDOZLOOWKHBDUHDEOHPDQDJHUVUDWKHUWKDQDIJXUHKHDGIRUWKHPHGLDDQGFDQHQJHQGHUHPSORBHHWUXVWFRPPLWPHQWDQGORBDOWBWKHBZLOODOVRKDYHDGHVLUHWRVKXQSXEOLFLWBFKDQQHODPEWLRQLQWRGHYHORSLQJWKHFRPSDQBQRWWKHPVHOYHVJLYHFUHGLWWRRWKHUVDURXQGWKHPDQGGHVSLVHPHGLRFULWBWRWRSRISDJHWRLQGHAZKDWDPHVVSDUWLFSDWLRQDVDVPSOHPDQDJHULDOUXOHWRFRPSOHALIBRUJDQLVDWLRQVDFWXDOOBDVHULRXVUHVHDUFKSDSHUZKLFKORRNVDWVRPHRIWKHVLPSOHUXOHVRIPDQDJHPHQWZKFKQWKHHQGFDQIRXOXSRXUOLYHVIRUJRRGEXWRQOBLIZHOHWWKHPZHDOOLDVVXPHNQRZRIWKHKRUVHPDGHEBDFRPPLWWHHLQWRGDBVFRQVXOWDWLYHFOPDWHZHFRXOGEHKHDGLQJIRUWUBLQJWRGHDOLQFDPHOVXQOHVVXOWLPDWHOBWKHPDQDJHULHWKHVLQJOHSHUVRQUHVSRQVLEOHIRUPDNLQJDQGLPSOHPHQWQJWKHGHFLVLRQGHFLGHVRXUKRUVHVVKRXOGQRWKDYHKXPSVZKHWKHURQHRUWZRLVLPPDWHULDOVRLQWKHHQGZHKDYHWKHDXWRFUDWLFGLFWDWRULDOYLFWRULDQSDUHQWZKRVHRIIVSULQJPLJKWLIGDULQJWRTXHVWLRQUHFHLYHWKHUHVSRQVHEHFDXVHLVDBLWLVMRXUQDORIPDQDJHPHQWVWXGLHVPDUFKXSGDWHFRPPHQWRQWKHRWKHUKDQGWKHHXURSHDQGLUHFWLYHVDBVWKRXVKDOWFRQVXOWDQGDWOHQJWKXQOHVVWKHUHDUHOHVVWKDQVWDIILQBRXURUJDQLVDWLRQVRUUBJXBVWKDWPHDQVWKDWLFDQFRQWLQXHWREHWKHDXWRFUDWFGFWDWRULDOSDUHQWWBSHDWOHDVWLQODZLIQRWUHDOLWBWRWRSRISDJHWRLQGHAOHDGHUVQHHGPRUHWUDLQLQJDBHDUDIWHUWKHOLEUDUBZRUOGVUHFUXWUHWDQDQGOHDGUHSRUWZDUQHGRIIDOOLQJVWDQGDUGVLQHAHFXWLYHDELOLWBPXVHXPVDUHIDFLQJDVLPODUOHDGHUVKLSFULVLVVSHDNLQJDWWKHDQQXDOPXVHXPGUHFWRUVFRQIHUHQFHOLCDPRVRIWKHFRXQFLOIRUHAFHOOHQFHLQPDQDJHPHQWDQGOHDGHUVKLSWROGGHOHJDWHVWKDWWKHBVKRXOGKHHGWKHGVTXHWEHLQJYRLFHGEBMXQLRUDQGPLGGOHPDQDJHUVLQWKHSXEOLFVHFWRUDFFRUGQJWRDUHFHQWUHSRUWRIMXQLRUDQGPLGGOHPDQDJHUVFODLPWKDWOHDGHUVKSQWKHLURUJDQLVDWLRQLVSRRUPVDPRVEHOLHYHVWKDWWKLVPDWWHUVEHFDXVHJRRGOHDGHUVFDQQVSLUHDQGHQHUJLVHWKHLUHPSORBHHVZKLFKKDVDSRVWYHHIIHFWRQSHUIRUPDQFHOLEUDUBDQGLQIRUPDWLRQXSGDWHMXOBYROWRWRSRISDJHWRLQGHASDWKWRWKHJDWHZDBLVFOHDUHGDBHDUDJRDQHQWUHSUHQHXUVHHNLQJKHOSWRVHWXSDFRPSDQBLQJODVJRZULVNHGEHLQJNQRFNHGGRZQLQDUXVKRIDJHQFLHVEUDQGLVKLQJPRUHWKDQGLIIHUHQWVXSSRUWSURGXFWVDQGVHUYLFHVQHZEXVLQHVVHVIDFHGDEHZLOGHULQJFKRLFHRIGLIIHUHQWSXEOLFVHFWRUDJHQFLHVSURYLGLQJDFFHVVWRRYHUEXVLQHVVVXSSRUWSDUWQHUVKSVPRVWOBNQRZQEBFRQIXVLQJWKUHHOHWWHUDFURQBPVBHWGHVSLWHWKHZHOWHURIVHUYLFHVDYDLODEOHZLWKOLWHUDOOBKXQGUHGVRIDGYLVHUVJUDQWVDQGWUDLQLQJVFKHPHVRQRIIHUUHVHDUFKVKRZHGWKDWJODVJRZXUJHQWOBQHHGHGWRILQGEHWWHUZDBVWRLPSURYHLWVEXVLQHVVELUWKUDWHDQGLWVLQGLJHQRXVFRPSDQBVXUYLYDOUDWHWKHYXOQHUDELOLWBRIVPDOODQGPHGLXPVLCHGHQWHUSULVHVVPHVWRIDLOXUHQWKHLUHDUOBBHDUVLVFOHDUDQGLQJODVJRZRQOBRIVPHVVXUYLYHORQJHUWKDQWKUHHBHDUVFRPSDUHGWRWKHQDWLRQDOWKUHHBHDUVXUYLYDOUDWHRIRQWRSRIORZHUWKDQDYHUDJHVXUYLYDOUDWHVJODVJRZDOVRKDGDSUREOHPZLWKHXURSHDQEXVLQHVVJUDQWVEHLQJOHIWXQFODLPHGEHFDXVHHOLJLEOHFRPSDQHVGGQRWDSSOBIRUWKHFDVKRQRIIHUGXQFDQWDQQDKLOOFKLHIHAHFXWLYHRIJODVJRZFKDPEHURIFRPPHUFHVHCHGWKHFKDQFHWRSRROWKHUHVRXUFHVRIWKHSULYDWHDQGSXEOFVHFWRUVLQDPDMRUHIIRUWWRDGGUHVVWKHVKRUWFRPLQJVRIWKHVBVWHPDQGFUHDWHDVQJOHSRLQWRIHQWUBIRUFRPSDQLHVVHHNQJKHOSDWDQBVWDJHRIWKHLUGHYHORSPHQWVPDOOEXVLQHVVJDWHZDBLVDWYDOHULHGDUURFKVFRWWLVKKHUDOGMXOBPBVFKRROGDBVZHUHWKHKDSSHVWGDBVRIPB";
            cipher = cipher.ToLower();

            //-------------------------------------------------
            // calculating freq's
            Dictionary<char, int> cipherfreqs = new Dictionary<char, int>();
            foreach (char c in cipher)
            {
                //letters
                if (cipherfreqs.ContainsKey(c))
                {
                    cipherfreqs[c] += 1;
                }
                else
                {
                    cipherfreqs.Add(c, 1);
                }

            }
            //-------------------------------------------------

            // sorting freq's
            cipherfreqs = cipherfreqs.OrderByDescending(u => u.Value).ToDictionary(z => z.Key, y => y.Value);
            //

            //-------------------------------------------------
            //final map
            Dictionary<char, char> map = new Dictionary<char, char>();
            for (int i = 0; i < 26; i++)
                map.Add(cipherfreqs.ElementAt(i).Key, givenfreq.ElementAt(i).Key);
            //-------------------------------------------------




            //-------------------------------------------------
            // to get key (not nessecary)
            string key = "";
            map = map.OrderBy(u => u.Value).ToDictionary(z => z.Key, y => y.Value);
            foreach (KeyValuePair<char, char> ch in map)
                key += ch.Key;
            Console.WriteLine("key is : " + key);
            //-------------------------------------------------



            //-------------------------------------------------
            // plain text
            string plain = "";

            for (int i = 0; i < cipher.Length; i++)
                plain += map[cipher[i]];

            return plain;
            //-------------------------------------------------




        }
    }
}